### ISSUE TITLE
Повысить тестабилити класса GameStore

### ISSUE THREAD

**Issue by molottva** [molottva/TeamWork#1]
Для повышения уровня тестабилити класса [GameStore.java](https://github.com/molottva/TeamWork/blob/gamestore/src/main/java/ru/netology/GameStore.java) предлагаю: 

- либо добавить геттеры на поля класса:
https://github.com/molottva/TeamWork/blob/4b289fd9b171a06d9dd96bcb377d960974cf3a50/src/main/java/ru/netology/GameStore.java#L9
https://github.com/molottva/TeamWork/blob/4b289fd9b171a06d9dd96bcb377d960974cf3a50/src/main/java/ru/netology/GameStore.java#L16

- либо в методе
https://github.com/molottva/TeamWork/blob/4b289fd9b171a06d9dd96bcb377d960974cf3a50/src/main/java/ru/netology/GameStore.java#L22
возвращать `List<Game> games`, а в методе
https://github.com/molottva/TeamWork/blob/4b289fd9b171a06d9dd96bcb377d960974cf3a50/src/main/java/ru/netology/GameStore.java#L46
возвращать `Map<String, Integer> playedTime`.

**Comment by Secktant** [comment]
Согласен
