### ISSUE TITLE
Метод sumGenre не суммирует время у одной добавленной игры у одного игрока

### ISSUE THREAD

**Issue by Secktant** [molottva/TeamWork#6]
**Описание:**
Метод     [public int sumGenre(String genre) {](https://github.com/molottva/TeamWork/blob/a980af3d0fe44e5589e5f71bb9db2566017fd94f/src/test/java/ru/netology/PlayerTest.java#L44) не суммирует время игр

**Шаги:**
1. Запустить [тест](https://github.com/molottva/TeamWork/blob/a980af3d0fe44e5589e5f71bb9db2566017fd94f/src/test/java/ru/netology/PlayerTest.java#L9-L21)

**Ожидаемый результат:**
3

**Фактический результат:**
0

**Консоль**
<details>
```java
org.opentest4j.AssertionFailedError: 
Expected :3
Actual   :0
<Click to see difference>


	org.opentest4j.AssertionFailedError: 
Expected :3
Actual   :0
```
</details>

**Comment by molottva** [comment]
Баг был в методе public int play(Game game, int hours). Метод не прибавлял игровое время игроку.
