### ISSUE TITLE
При добавлении отрицательного значения в метод play не выдаётся ошибка

### ISSUE THREAD

**Issue by Secktant** [molottva/TeamWork#8]
**Описание:**
При добавлении отрицательного значения в метод play не выдаётся ошибка Exception

**Шаги:**
1. Запустить [тест](https://github.com/molottva/TeamWork/blob/d0ce42592f3bc402be3df9e6c4f978cb9b076fb9/src/test/java/ru/netology/PlayerTest.java#L100-L112)

**Ожидаемый результат:**
Выводится ошибка

**Фактический результат:**
Ошибка не выводится

**Консоль:**
<details>
org.opentest4j.AssertionFailedError: Expected java.lang.Exception to be thrown, but nothing was thrown.
</details>

**Окружение:**

- Операционная система: Windows 10 Pro 21H1
- IDE: IntelliJ IDEA 2022.1.1 (Community Edition)
Java: OpenJDK 11.0.13

**Comment by molottva** [comment]
Баг исправлен. В тесте [эта строка](https://github.com/molottva/TeamWork/blob/d0ce42592f3bc402be3df9e6c4f978cb9b076fb9/src/test/java/ru/netology/PlayerTest.java#L107) кода лишняя.
![Скриншот 27 05 22_17 19 42](https://user-images.githubusercontent.com/99751507/170720347-cbbb3265-f070-4702-9aec-927e4097fd8a.png)
